# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    statistics_service.class: AppBundle\Service\StatisticsService
    
  

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    statistics_service:
        class: %statistics_service.class%
        arguments: [ "@doctrine.orm.entity_manager", "@service_container" ]