<?php

namespace AppBundle\Entity\Repository;

/**
 * Client
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Client extends \Doctrine\ORM\EntityRepository
{
//	public function findAll()
//	{
//		return array();
//	}

	
}
