<?php

namespace AppBundle\Entity\Repository;

/**
 * ProjectStatus
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectStatus extends \Doctrine\ORM\EntityRepository
{
}
