<?php

namespace AppBundle\Entity\Repository;

/**
 * Project
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Project extends \Doctrine\ORM\EntityRepository
{
}
