<?php

namespace AppBundle\Entity\Repository;

/**
 * StatusOfProject
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusOfProject extends \Doctrine\ORM\EntityRepository
{
}
