<?php

namespace AppBundle\Entity\Repository;

/**
 * StatusOfTask
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusOfTask extends \Doctrine\ORM\EntityRepository
{
}
