<?php

namespace AppBundle\Entity\Repository;

/**
 * Task
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Task extends \Doctrine\ORM\EntityRepository
{
}
