<?php

namespace AppBundle\Entity\Repository;

/**
 * Team
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Team extends \Doctrine\ORM\EntityRepository
{
}
