<?php

namespace AppBundle\Entity\Repository;

/**
 * TypeOfNotification
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOfNotification extends \Doctrine\ORM\EntityRepository
{
}
