<?php

namespace AppBundle\Entity\Repository;

/**
 * TypeOfClient
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOfClient extends \Doctrine\ORM\EntityRepository
{
}
