<?php

namespace AppBundle\Entity\Repository;

/**
 * Work
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Work extends \Doctrine\ORM\EntityRepository
{
}
